src/Entity/Organisation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrganisationRepository")
 */
class Organisation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $website;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone_nr;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZip(): ?string
    {
        return $this->zip;
    }

    public function setZip(string $zip): self
    {
        $this->zip = $zip;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNr(): ?int
    {
        return $this->phone_nr;
    }

    public function setPhoneNr(int $phone_nr): self
    {
        $this->phone_nr = $phone_nr;

        return $this;
    }

}

src/Form/OrganisationType.php
<?php

namespace App\Form;

use App\Entity\Organisation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrganisationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('address')
            ->add('zip')
            ->add('city')
            ->add('country')
            ->add('website')
            ->add('email')
            ->add('phone_nr')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Organisation::class,
        ]);
    }
}

src/Controller/OrganisationController.php
<?php

namespace App\Controller;

use App\Entity\Organisation;
use App\Form\OrganisationType;
use App\Repository\OrganisationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/organisation")
 */
class OrganisationController extends AbstractController
{
    /**
     * @Route("/", name="organisation_index", methods={"GET"})
     */
    public function index(OrganisationRepository $organisationRepository): Response
    {
        return $this->render('organisation/index.html.twig', [
            'organisations' => $organisationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="organisation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $organisation = new Organisation();
        $form = $this->createForm(OrganisationType::class, $organisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($organisation);
            $entityManager->flush();

            return $this->redirectToRoute('organisation_index');
        }

        return $this->render('organisation/new.html.twig', [
            'organisation' => $organisation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="organisation_show", methods={"GET"})
     */
    public function show(Organisation $organisation): Response
    {
        return $this->render('organisation/show.html.twig', [
            'organisation' => $organisation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="organisation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Organisation $organisation): Response
    {
        $form = $this->createForm(OrganisationType::class, $organisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('organisation_index', [
                'id' => $organisation->getId(),
            ]);
        }

        return $this->render('organisation/edit.html.twig', [
            'organisation' => $organisation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="organisation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Organisation $organisation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$organisation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($organisation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('organisation_index');
    }
}

templates/organisation/_delete_form.html.twig
<form method="post" action="{{ path('organisation_delete', {'id': organisation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ organisation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/organisation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/organisation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Organisation{% endblock %}

{% block body %}
    <h1>Edit Organisation</h1>

    {{ include('organisation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('organisation_index') }}">back to list</a>

    {{ include('organisation/_delete_form.html.twig') }}
{% endblock %}

templates/organisation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Organisation index{% endblock %}

{% block body %}
    <h1>Organisation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Address</th>
                <th>Zip</th>
                <th>City</th>
                <th>Country</th>
                <th>Website</th>
                <th>Email</th>
                <th>Phone_nr</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for organisation in organisations %}
            <tr>
                <td>{{ organisation.id }}</td>
                <td>{{ organisation.name }}</td>
                <td>{{ organisation.address }}</td>
                <td>{{ organisation.zip }}</td>
                <td>{{ organisation.city }}</td>
                <td>{{ organisation.country }}</td>
                <td>{{ organisation.website }}</td>
                <td>{{ organisation.email }}</td>
                <td>{{ organisation.phoneNr }}</td>
                <td>
                    <a href="{{ path('organisation_show', {'id': organisation.id}) }}">show</a>
                    <a href="{{ path('organisation_edit', {'id': organisation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('organisation_new') }}">Create new</a>
{% endblock %}

templates/organisation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Organisation{% endblock %}

{% block body %}
    <h1>Create new Organisation</h1>

    {{ include('organisation/_form.html.twig') }}

    <a href="{{ path('organisation_index') }}">back to list</a>
{% endblock %}

templates/organisation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Organisation{% endblock %}

{% block body %}
    <h1>Organisation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ organisation.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ organisation.name }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ organisation.address }}</td>
            </tr>
            <tr>
                <th>Zip</th>
                <td>{{ organisation.zip }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ organisation.city }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ organisation.country }}</td>
            </tr>
            <tr>
                <th>Website</th>
                <td>{{ organisation.website }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ organisation.email }}</td>
            </tr>
            <tr>
                <th>Phone_nr</th>
                <td>{{ organisation.phoneNr }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('organisation_index') }}">back to list</a>

    <a href="{{ path('organisation_edit', {'id': organisation.id}) }}">edit</a>

    {{ include('organisation/_delete_form.html.twig') }}
{% endblock %}