src/Entity/Payment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PaymentRepository")
 */
class Payment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $payment_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getPaymentDate(): ?\DateTimeInterface
    {
        return $this->payment_date;
    }

    public function setPaymentDate(?\DateTimeInterface $payment_date): self
    {
        $this->payment_date = $payment_date;

        return $this;
    }
}

src/Form/PaymentType.php
<?php

namespace App\Form;

use App\Entity\Payment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaymentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type')
            ->add('number')
            ->add('payment_date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Payment::class,
        ]);
    }
}

src/Controller/PaymentController.php
<?php

namespace App\Controller;

use App\Entity\Payment;
use App\Form\PaymentType;
use App\Repository\PaymentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/payment")
 */
class PaymentController extends AbstractController
{
    /**
     * @Route("/", name="payment_index", methods={"GET"})
     */
    public function index(PaymentRepository $paymentRepository): Response
    {
        return $this->render('payment/index.html.twig', [
            'payments' => $paymentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="payment_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $payment = new Payment();
        $form = $this->createForm(PaymentType::class, $payment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($payment);
            $entityManager->flush();

            return $this->redirectToRoute('payment_index');
        }

        return $this->render('payment/new.html.twig', [
            'payment' => $payment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="payment_show", methods={"GET"})
     */
    public function show(Payment $payment): Response
    {
        return $this->render('payment/show.html.twig', [
            'payment' => $payment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="payment_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Payment $payment): Response
    {
        $form = $this->createForm(PaymentType::class, $payment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('payment_index', [
                'id' => $payment->getId(),
            ]);
        }

        return $this->render('payment/edit.html.twig', [
            'payment' => $payment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="payment_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Payment $payment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$payment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($payment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('payment_index');
    }
}

templates/payment/_delete_form.html.twig
<form method="post" action="{{ path('payment_delete', {'id': payment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ payment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/payment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/payment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Payment{% endblock %}

{% block body %}
    <h1>Edit Payment</h1>

    {{ include('payment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('payment_index') }}">back to list</a>

    {{ include('payment/_delete_form.html.twig') }}
{% endblock %}

templates/payment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payment index{% endblock %}

{% block body %}
    <h1>Payment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Number</th>
                <th>Payment_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for payment in payments %}
            <tr>
                <td>{{ payment.id }}</td>
                <td>{{ payment.type }}</td>
                <td>{{ payment.number }}</td>
                <td>{{ payment.paymentDate ? payment.paymentDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('payment_show', {'id': payment.id}) }}">show</a>
                    <a href="{{ path('payment_edit', {'id': payment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('payment_new') }}">Create new</a>
{% endblock %}

templates/payment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Payment{% endblock %}

{% block body %}
    <h1>Create new Payment</h1>

    {{ include('payment/_form.html.twig') }}

    <a href="{{ path('payment_index') }}">back to list</a>
{% endblock %}

templates/payment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Payment{% endblock %}

{% block body %}
    <h1>Payment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ payment.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ payment.type }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ payment.number }}</td>
            </tr>
            <tr>
                <th>Payment_date</th>
                <td>{{ payment.paymentDate ? payment.paymentDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('payment_index') }}">back to list</a>

    <a href="{{ path('payment_edit', {'id': payment.id}) }}">edit</a>

    {{ include('payment/_delete_form.html.twig') }}
{% endblock %}