src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tel_nr;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $mobile_nr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $insertion_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $zip;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $country;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Organisation")
     */
    private $organisation_id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_activity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $function;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="user_id")
     */
    private $reservations;

    public function __construct()
    {
        parent::__construct();
        $this->reservations = new ArrayCollection();
    }

    public function getTelNr(): ?int
    {
        return $this->tel_nr;
    }

    public function setTelNr(?int $tel_nr): self
    {
        $this->tel_nr = $tel_nr;

        return $this;
    }

    public function getMobileNr(): ?int
    {
        return $this->mobile_nr;
    }

    public function setMobileNr(?int $mobile_nr): self
    {
        $this->mobile_nr = $mobile_nr;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getInsertionName(): ?string
    {
        return $this->insertion_name;
    }

    public function setInsertionName(?string $insertion_name): self
    {
        $this->insertion_name = $insertion_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZip(): ?string
    {
        return $this->zip;
    }

    public function setZip(string $zip): self
    {
        $this->zip = $zip;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return Collection|Organisation[]
     */
    public function getOrganisationId(): Collection
    {
        return $this->organisation_id;
    }

    public function addOrganisationId(Organisation $organisationId): self
    {
        if (!$this->organisation_id->contains($organisationId)) {
            $this->organisation_id[] = $organisationId;
            $organisationId->setFunction($this);
        }

        return $this;
    }

    public function removeOrganisationId(Organisation $organisationId): self
    {
        if ($this->organisation_id->contains($organisationId)) {
            $this->organisation_id->removeElement($organisationId);
            // set the owning side to null (unless already changed)
            if ($organisationId->getFunction() === $this) {
                $organisationId->setFunction(null);
            }
        }

        return $this;
    }

    public function getLastActivity(): ?\DateTimeInterface
    {
        return $this->last_activity;
    }

    public function setLastActivity(?\DateTimeInterface $last_activity): self
    {
        $this->last_activity = $last_activity;

        return $this;
    }

    public function getFunction(): ?string
    {
        return $this->function;
    }

    public function setFunction(string $function): self
    {
        $this->function = $function;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setUserId($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getUserId() === $this) {
                $reservation->setUserId(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('usernameCanonical')
            ->add('email')
            ->add('emailCanonical')
            ->add('enabled')
            ->add('salt')
            ->add('password')
            ->add('lastLogin')
            ->add('confirmationToken')
            ->add('passwordRequestedAt')
            ->add('roles')
            ->add('tel_nr')
            ->add('mobile_nr')
            ->add('first_name')
            ->add('insertion_name')
            ->add('last_name')
            ->add('address')
            ->add('zip')
            ->add('city')
            ->add('country')
            ->add('last_activity')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(): Response
    {
        $users = $this->getDoctrine()
            ->getRepository(User::class)
            ->findAll();

        return $this->render('user/index.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index', [
                'id' => $user->getId(),
            ]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Username</th>
                <th>UsernameCanonical</th>
                <th>Email</th>
                <th>EmailCanonical</th>
                <th>Enabled</th>
                <th>Salt</th>
                <th>Password</th>
                <th>LastLogin</th>
                <th>ConfirmationToken</th>
                <th>PasswordRequestedAt</th>
                <th>Roles</th>
                <th>Id</th>
                <th>Tel_nr</th>
                <th>Mobile_nr</th>
                <th>First_name</th>
                <th>Insertion_name</th>
                <th>Last_name</th>
                <th>Address</th>
                <th>Zip</th>
                <th>City</th>
                <th>Country</th>
                <th>Last_activity</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.usernameCanonical }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.emailCanonical }}</td>
                <td>{{ user.enabled ? 'Yes' : 'No' }}</td>
                <td>{{ user.salt }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.confirmationToken }}</td>
                <td>{{ user.passwordRequestedAt ? user.passwordRequestedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.roles ? user.roles|join(', ') : '' }}</td>
                <td>{{ user.id }}</td>
                <td>{{ user.telNr }}</td>
                <td>{{ user.mobileNr }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.insertionName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.address }}</td>
                <td>{{ user.zip }}</td>
                <td>{{ user.city }}</td>
                <td>{{ user.country }}</td>
                <td>{{ user.lastActivity ? user.lastActivity|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="23">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>UsernameCanonical</th>
                <td>{{ user.usernameCanonical }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>EmailCanonical</th>
                <td>{{ user.emailCanonical }}</td>
            </tr>
            <tr>
                <th>Enabled</th>
                <td>{{ user.enabled ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Salt</th>
                <td>{{ user.salt }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>LastLogin</th>
                <td>{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>ConfirmationToken</th>
                <td>{{ user.confirmationToken }}</td>
            </tr>
            <tr>
                <th>PasswordRequestedAt</th>
                <td>{{ user.passwordRequestedAt ? user.passwordRequestedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Tel_nr</th>
                <td>{{ user.telNr }}</td>
            </tr>
            <tr>
                <th>Mobile_nr</th>
                <td>{{ user.mobileNr }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Insertion_name</th>
                <td>{{ user.insertionName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ user.address }}</td>
            </tr>
            <tr>
                <th>Zip</th>
                <td>{{ user.zip }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ user.city }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ user.country }}</td>
            </tr>
            <tr>
                <th>Last_activity</th>
                <td>{{ user.lastActivity ? user.lastActivity|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}